*** Variables ***

${msg_do_you_really_want_to_logout}      Do you really want to logout?
${movie_name}                            1. Top Gun    
${home}      HOME
${series}    SERIES    
${movies}    MOVIES
${genre_movies}         GENRE
${genre_series}         GENRE
${devicerestriction}    DEVICE RESTRICTION
${recommendedforyou}    RECOMMENDED FOR YOU

${kids&family}    KIDS & FAMILY
${cartoons}  CARTOONS
