*** Variables ***

${msg_do_you_really_want_to_logout}       คุณต้องการออกจากระบบ ?
${movie_name}                             ท็อปกัน ฟ้าเหนือฟ้า
${home}     หน้าแรก 
${series}   ซีรีส์
${movies}   ภาพยนตร์
${genre_movies}         ประเภทภาพยนตร์
${genre_series}         ประเภทซีรีส์
${devicerestriction}    DEVICE RESTRICTION
${recommendedforyou}    แนะนำสำหรับคุณ

${kids&family}    เด็กและครอบครัว
${cartoons}  การ์ตูนสำหรับเด็ก
